# https://docs.github.com/cn/actions/automating-builds-and-tests/building-and-testing-python

name: Update dailynews

# 国际标准时间1点（北京时间9点）
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: ./install.sh

      - name: Push articles
        env:
          FEISHU_KEY: ${{ secrets.FEISHU_KEY }}
          WECOM_KEY: ${{ secrets.WECOM_KEY }}
          DINGTALK_KEY: ${{ secrets.DINGTALK_KEY }}
          QQ_KEY: ${{ secrets.QQ_KEY }}
          TELEGRAM_KEY: ${{ secrets.TELEGRAM_KEY }}
          MAIL_KEY: ${{ secrets.MAIL_KEY }}
          MAIL_RECEIVER: ${{ secrets.MAIL_RECEIVER }}
          BAIDU_APP_ID: ${{ secrets.BAIDU_APP_ID }}
          BAIDU_APP_SECRET: ${{ secrets.BAIDU_APP_SECRET }}
        run: python3 yarb.py

      - name: Commit
        run: |
          git diff
          git config --global user.email wuyuw515@gmail.com
          git config --global user.name wuyuw
          git add archive today.md
          git commit -m "每日安全资讯（`date +'%Y-%m-%d'`）"
          git pull --rebase origin main
          git push -f origin main

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ github.token }}

  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 7
          keep_minimum_runs: 7
